version: '2'
services:
  nomad-server-1:
    container_name: nomad-server-1
    command: /bin/nomad agent -config=/server.hcl
    environment:
      NOMAD_SERVER_HTTP_PORT: 4646
      NOMAD_SERVER_RPC_PORT: 4647
      NOMAD_SERVER_SERF_PORT: 4648
    image: rms1000watt/nomad:latest
    ports:
      - 4646:4646
      - 4647:4647
      - 4648:4648
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./server.hcl.tpl:/server.hcl.tpl

  nomad-server-2:
    container_name: nomad-server-2
    command: /bin/nomad agent -config=/server.hcl
    environment:
      NOMAD_SERVER_HTTP_PORT: 5646
      NOMAD_SERVER_RPC_PORT: 5647
      NOMAD_SERVER_SERF_PORT: 5648
      NOMAD_SERVER_ADDRESS_1: nomad-server-1:4648
    image: rms1000watt/nomad:latest
    ports:
      - 5646:5646
      - 5647:5647
      - 5648:5648
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./server.hcl.tpl:/server.hcl.tpl
    depends_on:
    - nomad-server-1

  nomad-client-1:
    container_name: nomad-client-1
    command: /bin/nomad agent -config=/client.hcl
    environment:
      NOMAD_CLIENT_HTTP_PORT: 5656
      NOMAD_SERVER_ADDRESS_1: nomad-server-1:4647
      NOMAD_SERVER_ADDRESS_2: nomad-server-2:5647
    image: rms1000watt/nomad:latest
    ports:
      - 5656:5656
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./client.hcl.tpl:/client.hcl.tpl
    depends_on:
    - nomad-server-1
    - nomad-server-2

  nomad-client-2:
    container_name: nomad-client-2
    command: /bin/nomad agent -config=/client.hcl
    environment:
      NOMAD_CLIENT_HTTP_PORT: 6666
      NOMAD_SERVER_ADDRESS_1: nomad-server-1:4647
      NOMAD_SERVER_ADDRESS_2: nomad-server-2:5647
    image: rms1000watt/nomad:latest
    ports:
      - 6666:6666
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./client.hcl.tpl:/client.hcl.tpl
    depends_on:
    - nomad-server-1
    - nomad-server-2
    