version: '2'
services:
  nomad-server-1:
    container_name: nomad-server-1
    command: /bin/nomad agent -config=/server.hcl
    image: rms1000watt/nomad:latest
    ports:
      - 4646:4646
      - 4647:4647
      - 4648:4648
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./server.hcl.tpl:/server.hcl.tpl

  nomad-client-1:
    container_name: nomad-client-1
    command: /bin/nomad agent -config=/client.hcl
    environment:
      NOMAD_CLIENT_PORT: 5656
    image: rms1000watt/nomad:latest
    ports:
      - 5656:5656
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./client.hcl.tpl:/client.hcl.tpl

  nomad-client-2:
    container_name: nomad-client-2
    command: /bin/nomad agent -config=/client.hcl
    environment:
      NOMAD_CLIENT_PORT: 6666
    image: rms1000watt/nomad:latest
    ports:
      - 6666:6666
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./client.hcl.tpl:/client.hcl.tpl
    